### ISSUE TITLE
你这插件连载入都做不到啊

### ISSUE THREAD

**Issue by Leoparking** [Chlna6666/Ranking#1]
[09:01:50] [Server thread/ERROR] [Minecraft]: Could not load 'plugins\[排行榜]Ranking-1.1.1-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `org.com.ranking.Ranking'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[forge-1.20.1-47.2.30-universal.jar%23239!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[forge-1.20.1-47.2.30-universal.jar%23239!/:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:396) ~[forge-1.20.1-47.2.30-universal.jar%23239!/:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:304) ~[forge-1.20.1-47.2.30-universal.jar%23239!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:437) ~[forge-1.20.1-47.2.30-universal.jar%23239!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:216) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23234!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: org.com.ranking.Ranking
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:186) ~[forge-1.20.1-47.2.30-universal.jar%23239!/:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:138) ~[forge-1.20.1-47.2.30-universal.jar%23239!/:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:89) ~[forge-1.20.1-47.2.30-universal.jar%23239!/:?]
	... 8 more

现场只留下这段话

**Comment by Leoparking** [comment]
使用PlugmanX手动加载时返回以下错误
> plugman load [排行榜]Ranking-1.1.1-SNAPSHOT
[09:08:16 WARN]: org.bukkit.plugin.InvalidPluginException: Cannot find main clas
s `org.com.ranking.Ranking'
[09:08:16 WARN]:        at com.rylinaux.plugman.util.BukkitPluginUtil.load(Bukki
tPluginUtil.java:418)
[09:08:16 WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(Load
Command.java:116)
[09:08:16 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(
PlugManCommandHandler.java:97)
[09:08:16 WARN]:        ... 15 more

**Comment by Chlna6666** [comment]
fix  Cannot find main class
