### ISSUE TITLE
不知道是咋回事

### ISSUE THREAD

**Issue by BigAppleClass** [Chlna6666/Ranking#2]
[09:25:15 ERROR]: Could not pass event PlayerJoinEvent to Ranking v1.1.2
java.lang.IllegalArgumentException: Entry cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scoreboard.CraftObjective.getScore(CraftObjective.java:140) ~[paper-1.20.4.jar:git-Paper-496]
        at com.chlna6666.ranking.Ranking.updateScoreboards(Ranking.java:323) ~[[排行]Ranking-1.1.2-SNAPSHOT.jar:?]
        at com.chlna6666.ranking.Ranking.onPlayerJoin(Ranking.java:382) ~[[排行]Ranking-1.1.2-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor406.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:345) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:134) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Chlna6666** [comment]
能否提供配置文件和插件存储的数据

**Comment by BigAppleClass** [comment]
已经没事了，我在win系统上加载的插件的文件，在linux上出了这个报错。我直接删了文件夹后重新生成的没有任何问题了。

**Comment by BigAppleClass** [comment]
顺便提个小建议，可以用一条指令输出全部排行嘛，一个一个查看有点点费劲

**Comment by Chlna6666** [comment]
> 顺便提个小建议，可以用一条指令输出全部排行嘛，一个一个查看有点点费劲

下个版本支持

**Comment by BigAppleClass** [comment]
爱你

**Comment by Chlna6666** [comment]
- 增加了 `ranking all` 指令，玩家可以通过该指令查看所有排行榜数据。
- 增加了 `ranking my` 指令，玩家可以通过该指令查看自己的所有排行榜数据。
- 增加了 `ranking list <ranking_name>` 指令，玩家可以通过该指令查看指定排行榜的数据。
